version: '3.8'

services:

  bot:
    build:
      context: .
    restart: on-failure
    stop_signal: SIGINT
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - test.env
    environment:
      - REDIS_HOST=redis
    healthcheck:
      test: python3 health.py || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    restart: on-failure
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    command: >
      --requirepass 123456
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
    driver: "local"
